### ISSUE TITLE
Can you release a statically built package?

### ISSUE THREAD

**Issue by recover-sanity** [Rosentti/ksysguard-plasma6#1]
I'm trying to use the PKGBUILD found in this repo and I'm unable to successfully build it due to library errors most likely due to the KDE6 release and I'm wondering would it be possible for you to compile ksysguard statically so it'll work on most systems?

**Comment by Rosentti** [comment]
Hi, I don't really work on this project anymore. There's another package for arch: `ksysguard6-git`, which is made by a different dev. 
I use it myself now.
